# Streamlit theme configuration

# Note: These theme settings apply to local development only.
# When deployed to Hugging Face Spaces, the theme will be determined by
# the 'colorFrom'/'colorTo' settings in the README.md file.

[theme]
primaryColor = "#5867FF"  # Local button color
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Server configuration
[server]
enableCORS = false
enableXsrfProtection = true

# Logger configuration
[logger]
level = "info"